import type { Metadata } from 'next'
import './globals.css'
import { notoSans } from '@/lib/fonts'
import { Credits } from '@/components/Credits/Credits'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        {children}
        <Credits />
      </body>
    </html>
  )
}
